---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/customers":
    get:
      summary: list customers
      responses:
        '200':
          description: successful
  "/customers/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show customer
      responses:
        '200':
          description: successful
  "/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                reservation:
                  value:
                  - id: 32a0b18a-98a2-4610-a284-c6a79d35f7d4
                    customer_id: f835547b-a0eb-462e-823e-f7688cdecfce
                    table_id: 1e78b073-608f-4662-813d-430b807998a3
                    restaurant_id: 252d7e7f-b794-4b7a-9639-4f6ff1a3974d
                    start_at: 1080
                    end_at: 1140
                    number_of_guests: 2
                    state: assigned
                    date_of_reservation: '2024-09-07T23:14:01.654Z'
                    created_at: '2024-09-06T23:14:01.667Z'
                    updated_at: '2024-09-06T23:14:01.667Z'
                  - id: 32a0b18a-98a2-4610-a284-c6a79d35f7d4
                    customer_id: f835547b-a0ab-462e-823e-f7688cdecf12
                    table_id: 1e78b073-608f-4662-813d-430b807998a3
                    restaurant_id: 252d7e7f-b794-4b7a-9639-4f6ff1a3974d
                    start_at: 980
                    end_at: 1040
                    number_of_guests: 4
                    state: assigned
                    date_of_reservation: '2024-09-07T23:14:01.654Z'
                    created_at: '2024-09-06T23:14:01.667Z'
                    updated_at: '2024-09-06T23:14:01.667Z'
    post:
      summary: create reservation optimized
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                reservation:
                  value:
                    id: 32a0b18a-98a2-4610-a284-c6a79d35f7d4
                    customer_id: f835547b-a0eb-462e-823e-f7688cdecfce
                    table_id: 1e78b073-608f-4662-813d-430b807998a3
                    restaurant_id: 252d7e7f-b794-4b7a-9639-4f6ff1a3974d
                    start_at: 1080
                    end_at: 1140
                    number_of_guests: 2
                    state: assigned
                    date_of_reservation: '2024-09-07T23:14:01.654Z'
                    created_at: '2024-09-06T23:14:01.667Z'
                    updated_at: '2024-09-06T23:14:01.667Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: string
                restaurant_id:
                  type: string
                start_at:
                  type: string
                end_at:
                  type: string
                number_of_guests:
                  type: string
                date_of_reservation:
                  type: string
                optimized:
                  type: string
  "/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                reservation:
                  value:
                    id: 32a0b18a-98a2-4610-a284-c6a79d35f7d4
                    customer_id: f835547b-a0eb-462e-823e-f7688cdecfce
                    table_id: 1e78b073-608f-4662-813d-430b807998a3
                    restaurant_id: 252d7e7f-b794-4b7a-9639-4f6ff1a3974d
                    start_at: 1080
                    end_at: 1140
                    number_of_guests: 2
                    state: assigned
                    date_of_reservation: '2024-09-07T23:14:01.654Z'
                    created_at: '2024-09-06T23:14:01.667Z'
                    updated_at: '2024-09-06T23:14:01.667Z'
  "/restaurants/{restaurant_id}/reservations":
    parameters:
    - name: restaurant_id
      in: path
      description: restaurant_id
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                reservation:
                  value:
                  - id: 32a0b18a-98a2-4610-a284-c6a79d35f7d4
                    customer_id: f835547b-a0eb-462e-823e-f7688cdecfce
                    table_id: 1e78b073-608f-4662-813d-430b807998a3
                    restaurant_id: 252d7e7f-b794-4b7a-9639-4f6ff1a3974d
                    start_at: 1080
                    end_at: 1140
                    number_of_guests: 2
                    state: assigned
                    date_of_reservation: '2024-09-07T23:14:01.654Z'
                    created_at: '2024-09-06T23:14:01.667Z'
                    updated_at: '2024-09-06T23:14:01.667Z'
                  - id: 32a0b18a-98a2-4610-a284-c6a79d35f7d4
                    customer_id: f835547b-a0ab-462e-823e-f7688cdecf12
                    table_id: 1e78b073-608f-4662-813d-430b807998a3
                    restaurant_id: 252d7e7f-b794-4b7a-9639-4f6ff1a3974d
                    start_at: 980
                    end_at: 1040
                    number_of_guests: 4
                    state: assigned
                    date_of_reservation: '2024-09-07T23:14:01.654Z'
                    created_at: '2024-09-06T23:14:01.667Z'
                    updated_at: '2024-09-06T23:14:01.667Z'
  "/restaurants/{restaurant_id}/reservations/{id}":
    parameters:
    - name: restaurant_id
      in: path
      description: restaurant_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
  "/restaurants":
    get:
      summary: list restaurants
      responses:
        '200':
          description: successful
  "/restaurants/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show restaurant
      responses:
        '200':
          description: successful
  "/servers":
    get:
      summary: list servers
      responses:
        '200':
          description: successful
  "/servers/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show server
      responses:
        '200':
          description: successful
  "/restaurants/{restaurant_id}/tables":
    parameters:
    - name: restaurant_id
      in: path
      description: restaurant_id
      required: true
      schema:
        type: string
    get:
      summary: list tables
      responses:
        '200':
          description: successful
  "/restaurants/{restaurant_id}/tables/{id}":
    parameters:
    - name: restaurant_id
      in: path
      description: restaurant_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show table
      responses:
        '200':
          description: successful
  "/tables/occupied?date_of_reservation={date_of_reservation}&start_at={start_at}&end_at={end_at}":
    parameters:
    - name: date_of_reservation
      in: path
      description: date_of_reservation
      required: true
      schema:
        type: string
    - name: start_at
      in: path
      description: start_at
      required: true
      schema:
        type: string
    - name: end_at
      in: path
      description: end_at
      required: true
      schema:
        type: string
    get:
      summary: occupied tables
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                tables:
                  value:
                  - id: f2780449-2af1-4611-848f-606e560b9de7
                    identifier: '20'
                    number_of_seats: 6
                    active: true
                    restaurant_id: fabdd375-03ed-47bd-8b68-3d730a6298b0
                    created_at: '2024-09-06T20:24:08.166Z'
                    updated_at: '2024-09-06T20:24:08.166Z'
                  - id: 605fb246-46ed-4afc-98fb-323f7785d423
                    identifier: '25'
                    number_of_seats: 2
                    active: true
                    restaurant_id: 252d7e7f-b794-4b7a-9639-4f6ff1a3974d
                    created_at: '2024-09-06T20:24:08.183Z'
                    updated_at: '2024-09-06T20:24:08.183Z'
                  - id: a7dcc970-b615-4f91-8f64-16d0f86a0691
                    identifier: '31'
                    number_of_seats: 8
                    active: true
                    restaurant_id: 53c89f01-92f9-46b0-8df8-128143fc5e10
                    created_at: '2024-09-06T20:24:08.202Z'
                    updated_at: '2024-09-06T20:24:08.202Z'
                  - id: 254c1896-9611-4c95-b8b9-b75ffb320387
                    identifier: '34'
                    number_of_seats: 6
                    active: true
                    restaurant_id: c8eb4cd2-99a1-4b02-8230-9ff6038f0cff
                    created_at: '2024-09-06T20:24:08.211Z'
                    updated_at: '2024-09-06T20:24:08.211Z'
                  - id: ee065406-d273-4af9-90f7-eaefca65c943
                    identifier: '37'
                    number_of_seats: 6
                    active: true
                    restaurant_id: 68e7d183-ec0d-4884-98b0-3a36a8ca4b19
                    created_at: '2024-09-06T20:24:08.220Z'
                    updated_at: '2024-09-06T20:24:08.220Z'
                  - id: 1da1c4ff-a9d8-47f0-a81e-1585d046e509
                    identifier: '48'
                    number_of_seats: 6
                    active: true
                    restaurant_id: eaa183f0-3c3a-4028-8328-c6a01a4b530e
                    created_at: '2024-09-06T20:24:08.261Z'
                    updated_at: '2024-09-06T20:24:08.261Z'
  "/tables":
    get:
      summary: list tables
      responses:
        '200':
          description: successful
  "/tables/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show table
      responses:
        '200':
          description: successful
servers:
- url: https://localhostisbesthost
  variables:
    defaultHost:
      default: www.localhost.com
