default: &default
  adapter: postgresql
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  timeout: 5000
  username: test
  password: blah

test:
  <<: *default
  database: dd_test

production:
  <<: *default
  database: dd_prod

development:
  <<: *default
  database: dd_dev